### ISSUE TITLE
Create home page frontend (mock)

### ISSUE THREAD

**Issue by Mikhaelle** [UnBArqDsw/2020.1_G2_TCLDL#121]
**_Issue_ type**

US X - Create home page frontend mock - without integration with papers

**Description**
Create home page frontend mock - without integration with papers

**Tasks**
- [ ] Create home page frontend
- [ ] Create submission and review buttons in navbar

**Acceptance Criteria**
-  [ ] Depending on the type of user enable the review and submission buttons
