### ISSUE TITLE
Create Crud Paper

### ISSUE THREAD

**Issue by Mikhaelle** [UnBArqDsw/2020.1_G2_TCLDL#122]
**_Issue_ type**

US X - Create Crud Paper

**Description**

**Tasks**
- [ ] Create paper entity
- [ ] Create endpoint to create
- [ ] Create endpoint to update
- [ ] Create endpoint to delete

**Acceptance Criteria**
- [ ] Rote that create a paper
- [ ] Rote that update a paper
- [ ] Rote that delete a paper
- [ ] Get papers by domain
- [ ] Get papers by user
- [ ] Get Papers that Need review
