### ISSUE TITLE
Create Submission Screen

### ISSUE THREAD

**Issue by Mikhaelle** [UnBArqDsw/2020.1_G2_TCLDL#123]
**_Issue_ type**

US X - _

**Description**

Tell us about your _issue_ here.

**Tasks**
- [ ] Add the submission route
- [ ] Add the form for creating paper
- [ ] Integrate with the back

**Acceptance Criteria**
- [ ]
