### ISSUE TITLE
Backend and database static diagrams

### ISSUE THREAD

**Issue by lorryaze** [UnBArqDsw/2020.1_G2_TCLDL#57]
**_Issue_ type**
DOC X - _Issue_  title  [Documentation]

**Description**

Make the diagrams for the entire backend structure and choose the most appropriate diagrams for each feature. 

Examples of  diagrams to be made: 

- class diagram
- component diagram
- package diagram

**Screenshots**

If you think that it would be necessary, add screenshots here to help you explain your _issue_.

**Tasks**
- [ ] reference the documentation
- [ ] make all the diagrams cited in the description of the issue
- [ ] look for more possibles diagrams that could be done for this module 
- [ ] make the artifacts available here tracked
  

**Acceptance Criteria**
- [ ] criteria 1
- [ ] ...

**Comment by Mikhaelle** [comment]
**Starting class diagram**
Version 1 in the image, note that it is only the first version and there is still much to be improved: 
![Untitled Diagram (2)](https://user-images.githubusercontent.com/22429549/93620810-f8aeff80-f9b0-11ea-8d59-1232acbd9a4b.png)

I would like to discuss some things
1º - I am having difficulty demonstrating that admins can submit papers but not review their own, I accept suggestions
2º - The relationship between user and questionnaire is weak (1 to 1) I place the questionnaire class next to the user's or I leave it as a separate class. I honestly still don't understand why a questionnaire in the scope of the discipline, but as it is tracked in the prototype I added it as a class
3º - Do not know what type of attributes are marked with ? in the paper class and I would like you to review the other attributes type as well
4º - How to demonstrate that subAdmin has priority in reviews through this diagram?

**Comment by Mikhaelle** [comment]
Will you want to do database and deployment diagram? 
Not tracked in the issue description

**Comment by Mikhaelle** [comment]
@ygortgaleno @VitorMeirelesOliveira can we do the package diagram together today?

**Comment by VitorMeirelesOliveira** [comment]
Yes! Is it ok at night?

**Comment by lorryaze** [comment]
> Will you want to do database and deployment diagram?
> Not tracked in the issue description

Yes, at least the database diagrams need to be done

**Comment by VitorMeirelesOliveira** [comment]
> **Starting class diagram**
> Version 1 in the image, note that it is only the first version and there is still much to be improved:
> ![Untitled Diagram (2)](https://user-images.githubusercontent.com/22429549/93620810-f8aeff80-f9b0-11ea-8d59-1232acbd9a4b.png)
> 
> I would like to discuss some things
> 1º - I am having difficulty demonstrating that admins can submit papers but not review their own, I accept suggestions
> 2º - The relationship between user and questionnaire is weak (1 to 1) I place the questionnaire class next to the user's or I leave it as a separate class. I honestly still don't understand why a questionnaire in the scope of the discipline, but as it is tracked in the prototype I added it as a class
> 3º - Do not know what type of attributes are marked with ? in the paper class and I would like you to review the other attributes type as well
> 4º - How to demonstrate that subAdmin has priority in reviews through this diagram?

1 -> Maybe use a restriction, like this "{must be different admin}"
2 -> Besides is weak, it`s good to keep it alongside the user.
3 -> It seems to be number type(long).
4 -> Maybe restriction, again. Like this "{subAdmin has priority to review}"

**Comment by Mikhaelle** [comment]
Thank you Vitor, for the feedback 

Version 2 - Class Diagram: https://drive.google.com/file/d/1boDtBtpG_AEh9RERRJR3p0bTZnvDa0F-/view?usp=sharing

![BackClassDiagram (3)](https://user-images.githubusercontent.com/22429549/93820383-797d2e00-fc33-11ea-9080-5c7d3fa03749.png)


Some doubts were answered by telegram and confirmed with the documentation:
1) between the paper and the domain, there is a relationship 1 paper has a domain and a domain has several papers but can they exist? YES

2) Can a paper have multiple users because of the co-author? YES

3) Can a subadmin become an admin? 

4) what types of graphics exist? performance x computing power and performance x time

5)Each datapoint of a graph represents a model, which is in a paper, which has a benchmark, which is within a domain

**Comment by Mikhaelle** [comment]
BackEnd class diagram for mail service: I accept suggestions

![Untitled Diagram (3)](https://user-images.githubusercontent.com/22429549/94096429-754f3d00-fdfa-11ea-8836-f0ab2c2a06d6.png)

**Comment by Mikhaelle** [comment]
Back Package Diagram for Paper Service : I accept suggestions 


![Untitled Diagram (6)](https://user-images.githubusercontent.com/22429549/94096555-c4956d80-fdfa-11ea-8aa9-fd6758c789e2.png)
