### ISSUE TITLE
Frontend static diagrams

### ISSUE THREAD

**Issue by lorryaze** [UnBArqDsw/2020.1_G2_TCLDL#58]
**_Issue_ type**
DOC X - _Issue_  title  [Documentation]

**Description**

Make the diagrams for the entire backend structure and choose the most appropriate diagrams for each feature. 

Examples of  diagrams to be made: 

- class diagram
- component diagram
- package diagram

**Screenshots**

If you think that it would be necessary, add screenshots here to help you explain your _issue_.

**Tasks**
- [ ] reference the documentation
- [ ] make all the diagrams cited in the description of the issue
- [ ] look for more possibles diagrams that could be done for this module 
- [ ] make the artifacts available here tracked
  

**Acceptance Criteria**
- [ ] criteria 1
- [ ] ...

**Comment by lorryaze** [comment]
The diagrams done to this phase are the component diagram and package diagram, the diagrams could be find at this link: 

[https://app.diagrams.net/#G1dcQAJhmG867BtXfA-kMhjcHH4JmpcE08](link)

Wevalidated the diagrams with Professor Milene, the component diagram for a first version is fine and the package diagram needs some corrections
