### ISSUE TITLE
User case diagram

### ISSUE THREAD

**Issue by lorryaze** [UnBArqDsw/2020.1_G2_TCLDL#59]
**_Issue_ type**
DOC X - _Issue_  title  [Documentation]

**Description**

Make the user case diagram

**Screenshots**

If you think that it would be necessary, add screenshots here to help you explain your _issue_.

**Tasks**
- [x] reference the documentation
- [x] make all the diagrams cited in the description of the issue
- [x] link or reference the user stories
- [x] make the artifacts available here tracked
  

**Acceptance Criteria**
- [ ] criteria 1
- [ ] ...

**Comment by mansogf** [comment]
Done (and validated by Milene).
