### ISSUE TITLE
Frontend Dynamic Diagrams

### ISSUE THREAD

**Issue by Mikhaelle** [UnBArqDsw/2020.1_G2_TCLDL#61]
**_Issue_ type**

DOC X - Issue title [Documentation]

**Description**
make the dynamic diagrams for the entire frontEnd structure and choose the most appropriate diagrams for each feature.

Examples of  diagrams to be made: 

- Sequence Diagram
- Communication Diagram
- Activity Diagram
- State Diagram

**Screenshots**

**Tasks**
- [ ] reference the documentation
- [ ] make all the diagrams cited in the description of the issue
- [ ] look for more possibles diagrams that could be done for this module 
- [ ] make the artifacts available here tracked

**Acceptance Criteria**
- [ ] Requirements tracking
- [ ] Versioning
- [ ] Documentation on ghpages

**Comment by lorryaze** [comment]
Os diagramas de sequência já foram feitos e estará na documentação assim que alguém aceitar o pr.
