### ISSUE TITLE
BackEnd Dynamic Diagrams

### ISSUE THREAD

**Issue by Mikhaelle** [UnBArqDsw/2020.1_G2_TCLDL#62]
**_Issue_ type**

DOC X - Issue title [Documentation]

**Description**
make the dynamic diagrams for the entire BackEnd structure and choose the most appropriate diagrams for each feature.

Examples of  diagrams to be made: 

- Sequence Diagram
- Communication Diagram
- Activity Diagram
- State Diagram

**Screenshots**

**Tasks**
- [ ] reference the documentation
- [ ] make all the diagrams cited in the description of the issue
- [ ] look for more possibles diagrams that could be done for this module 
- [ ] make the artifacts available here tracked

**Acceptance Criteria**
- [ ] Requirements tracking
- [ ] Versioning
- [ ] Documentation on ghpages

**Comment by mansogf** [comment]
I will do:

- Activity Diagram UML

**Comment by Mikhaelle** [comment]
I will do:

- State Diagram UML

**Comment by VitorMeirelesOliveira** [comment]
I'm doing a communication diagram
